# Generated by Django 5.0.7 on 2024-08-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_rename_image_imagemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='ai_image',
            field=models.ImageField(upload_to='ai_images/'),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='real_image',
            field=models.ImageField(upload_to='real_images/'),
        ),
    ]
